=head1 NAME

PMP::slurm - a subclass of PMP for the open source Slurm workload
manager.

=head1 SYNOPSIS

See the PMP documentation for a cogent synopsis.

=head1 DESCRIPTION

A subclass of PMP, it uses SLURM to submit its
jobs. The advantage of course is that stages that do not depend on
each other can be executed in parallel. Naturally requires Slurm to be
installed on the system.

=head1 OVERVIEW

PMP::slurm is used exactly like its superclass PMP. In terms of implementation
all that PMP::slurm does is overwrite the execStage method of PMP. See
the PMP documentation for all the gory details.


