=head1 NAME

PMPpbs - a subclass of PMP for batched processing.

=head1 SYNOPSIS

See the PMP documentation for a cogent synopsis.

=head1 DESCRIPTION

A subclass of PMP, it uses the Portable Batch System to submit its
jobs. The advantage of course is that stages that do not depend on
each other can be executed in parallel. Naturally requires PBS to be
installed on the system.

=head1 OVERVIEW

PMPpbs is used exactly like its superclass PMP. There are two
additional methods, setQueue and setHosts, for setting the batch
queue and the batch hosts respectively. In terms of implementation
all that PMPpbs does is overwrite the execStage method of PMP. See
the PMP documentation for all the gory details.
